version: '3.8'

services:
  # web:
  #   build: .
  #   ports:
  #     - "8080:8080"
  #   depends_on:
  #     - postgres

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
